site_name: Paper Notes
site_url: https://wz108578656.github.io/paper-notes-site/
repo_url: https://github.com/wz108578656/paper-notes-site
edit_uri: ''

extra:
  generator: false

theme:
  name: material
  language: zh
  features:
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/body_class.js

nav:
  - Home: index.md
  - Recent:
      - Recent: collections/Recent/index.md
      - InterStellar 2.0 (论文笔记): notes_repo/interstellar-20-fine-grained-streamguided-hwsw-co-design-for-multi-channel-dram-performance-steering/paper_notes/index.md
      - InterStellar 2.0 (通俗版): notes_repo/interstellar-20-fine-grained-streamguided-hwsw-co-design-for-multi-channel-dram-performance-steering/ELI5_notes/index.md
      - RISC-V Co-Processor (论文笔记): notes_repo/a-configurable-risc-v-co-processor-with-instruction-controlled-stream-based-accelerators/paper_notes/index.md
      - RISC-V Co-Processor (通俗版): notes_repo/a-configurable-risc-v-co-processor-with-instruction-controlled-stream-based-accelerators/ELI5_notes/index.md
      - MPU (论文笔记): notes_repo/the-memory-processing-unit-a-generalized-interface-for-end-to-end-in-memory-execution/paper_notes/index.md
      - MPU (通俗版): notes_repo/the-memory-processing-unit-a-generalized-interface-for-end-to-end-in-memory-execution/ELI5_notes/index.md
      - CD27 (论文笔记): notes_repo/cd27-mediated-regulatory-t-cell-depletion-and-effector-t-cell-costimulation-both-contribute-to-antitumor-efficacy/paper_notes/index.md
      - CD27 (通俗版): notes_repo/cd27-mediated-regulatory-t-cell-depletion-and-effector-t-cell-costimulation-both-contribute-to-antitumor-efficacy/ELI5_notes/index.md